name: CodeCov
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.9
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: 5.0

      - name: 'generate report'
        env:
          API_KEY: ${{ secrets.API_KEY }}
          ALGORITHM: ${{ secrets.ALGORITHM }}
          MONGO_DB_URL: ${{ secrets.MONGO_DB_URL }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          python -m pip install --upgrade pip          
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          coverage run -m pytest
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          flags: pytest
          fail_ci_if_error: true
