name: CodeCov
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:5.0.5
        env:
          MONGO_INITDB_ROOT_USERNAME: authmicroservice
          MONGO_INITDB_ROOT_PASSWORD: authmicroservice
        ports:
          - 27017:27017
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.9
      - name: 'Generate report'
        env:
          API_KEY: ${{ secrets.API_KEY }}
          MONGO_DB_URL: mongodb://authmicroservice:authmicroservice@127.0.0.1:27017/?retryWrites=true&w=majority
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          python -m pip install --upgrade pip          
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pytest --cov app
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
